### ISSUE TITLE
Nice crypto virus inside lol

### ISSUE THREAD

**Issue by FreeYoutubeViews** [MATRIX305/Youtube-Livestream-bot#4]
If you guys want NO VIRUS or Bitcoin malware just use my tools: https://dbtechlabs.com/
Not FREE but paid = guarantee!! REMEMBER ALL FREE things "smells" viruses as normal developer will NOT work hard and then give free youtube bots!

PS: Salut to all kiddos who download this crap nd run in admin mode :D :D

**Comment by MATRIX305** [comment]
lmao XDDD
XDDD you have to speak ill of others to sell your "programs" the repository has the source code and they can verify that it is a false positive, because the program does not have an XDDD signature
